### ISSUE TITLE
vs noodles and bedder-rs and rust-bio

### ISSUE THREAD

**Issue by Kentalot** [noamteyssier/bedrs#112]
Hi,

I was looking into bed support in my rust code and saw that this repo, noodles, rust-bio, and bedder-rs had bed support.  I think the 3 besides rust-bio are aiming for bedtools-like abilities.  Have you looked at the other repos and found any big differences?  What advantages and disadvantages do you think your repo has?  Thanks a lot and I'll keep an eye on the project.

**Comment by noamteyssier** [comment]
Hey @Kentalot - that's a good question and I think each of the crates you mentioned were developed and optimized for different purposes.

## Noodles
`noodles` is focused on being a general IO library for bioinformatics formats. You won't find any of the actual set operation algorithms implemented in that library. However, if you're just looking to read in files and extract information from records this might be the ideal choice for you. 

## Rust-Bio
`rust-bio` is a larger more algorithmic focused library in bioinformatics. It works well for a lot of tasks but I've found in my hands that the codebase can be heavy or clunky to work with and generally homespun versions of the algorithms (I've used) have been faster and easier to drop into existing tools. In terms of interval operations you'll find a few, but they're focused on intervals that are on the same chromosome and same strand (i.e. checking to see if a query interval is within the range of range without considering whether they're on the same chromosome or strand). 

## Bedder-rs
`bedder-rs` I only recently discovered - and it also looks very promising! It's developed by the Quinlan lab who were the original developers of BEDTools. It seems the project is still in early days though and many of the core implementations are not developed yet. 

## Bedrs

### Advantages 
`bedrs` is really focused on being a highly optimized and complete toolkit for genomic interval operations. The design is built around abstract interval types (see [Coordinates](https://docs.rs/bedrs/latest/bedrs/#coordinates)) and abstract interval containers (see [Containers](https://docs.rs/bedrs/latest/bedrs/#container)). 

The library currently is feature rich and lets you perform a lot of set operations directly in rust without needing to go through a command-line interface. For example, you can create a container of intervals and [subtract](https://docs.rs/bedrs/latest/bedrs/traits/container/trait.SetSubtract.html) a query from the set, or you can take the [complement](https://docs.rs/bedrs/latest/bedrs/traits/container/trait.Complement.html) of a single container of intervals, or just perform direct [overlaps](https://docs.rs/bedrs/latest/bedrs/traits/interval/trait.Overlap.html) between two intervals or see if they [border](https://docs.rs/bedrs/latest/bedrs/traits/interval/trait.Overlap.html#method.borders) each other or are [contained](https://docs.rs/bedrs/latest/bedrs/traits/interval/trait.Overlap.html#method.contains) by another interval. The library is also highly documented and full of specific unit tests for each function - which additionally shows how to actually perform the operations and what expected inputs and outputs of functions are. 

Currently I think that `bedrs` is the most feature-rich library in this respect. 

It's also written fully generically with traits, which lets you define custom interval types and really lets you optimize for your specific use case as each implementation is compiled monomorphically. This can lead to some major runtime performance increases and is one of the reasons why `gia` performed so well in the benchmarks.  

### Disadvantages

However, the core library is not focused at all on IO, but the implementation of reading in BED files and converting them to a built-in interval type (like a [GenomicInterval](https://docs.rs/bedrs/latest/bedrs/types/record/struct.GenomicInterval.html)) is very easy to do as you can deserialize a [CSV reader](https://docs.rs/csv/latest/csv/) into whatever type you want using [Serde](https://serde.rs/) which is what I do in [GIA](https://github.com/noamteyssier/gia). 

If you're interested in what this looks like you can see an example of what it looks like to create a container of `GenomicIntervals` from a file [here](https://github.com/noamteyssier/gia/blob/f3fb34566ce924b22535e8d0cbad5c4147885b1b/src/io/read/bed3.rs#L40-L55).

I'd say this may be the biggest disadvantage to the library - as currently all IO operations must be handled by the user. But they are not too difficult to implement and there are many examples of how to do so well in the GIA codebase. 

Another potential disadvantage is that the generics and traits can sometimes be unwieldy to handle and function signatures can start looking like algebra - but if you know your concrete type - such as a `GenomicInterval<usize>` - the ecosystem becomes much simpler and function signatures simplify tremendously.

## Other Libraries
The libraries you mentioned are bioinformatics focused and more popular - but there are others I could mention here (and I mention in my docs) that are deeper cuts, related, and worth mentioning again as potential alternatives for specific use cases:

- [rampart](https://crates.io/crates/rampart)
- [rust-lapper](https://crates.io/crates/rust-lapper)
- [COI-trees](https://crates.io/crates/coitrees)

## Overall
To be honest though I think it is difficult to give a recommendation to use one over another without knowing the specific use case as some advantages are disadvantages in a different context - but hopefully this was helpful to see the lay of the land in this space.

**Comment by Kentalot** [comment]
Wow, thanks so much for the detailed and honest feedback!  I will look into each some more and post any other findings I might discover over time trying the different repos.  Thanks!
